---
-   name: "Copying Backend Codebase"
    become: true
    copy:
        src: /root/project/backend
        dest: /home/ubuntu

-   name: "Removing existing Backend service"
    ignore_errors: yes
    shell: |
        cd /home/ubuntu/backend
        pm2 stop backend
        pm2 delete backend

-   name: "Installing and Building Backend"
    become: true
    shell: |
        cd /home/ubuntu/backend    
        npm i && npm run build  

-   name: "Running Backend service"
    become: true
    shell: |
        cd /home/ubuntu/backend
        pm2 install typescript  
        pm2 start npm --no-automation --name "backend" -- run start
