---
-   name: "Copying Backend Codebase"
    become: true
    copy:
        src: /root/project/backend
        dest: /home/ubuntu

-   name: "Removing existing Backend service"
    ignore_errors: yes
    shell: |
        cd /home/ubuntu/backend
        pm2 stop backend
        pm2 delete backend

-   name: "Installing and Building Backend"
    become: true
    shell: |
        cd /home/ubuntu/backend    
        npm i && npm run build  

-   name: "Running DB migrations and saving to MemStash.io"
    become: true
    shell: |
        cd /home/ubuntu/backend
        npm run migrations > migrations.txt
        cat migrations.txt
        curl -H "Content-Type: text/plain" -H "token: b5e154a8-0ab1-41c6-8855-47f61d4f7873" --request PUT --data $(grep -c "Migrations are not pending" migrations.txt) https://api.memstash.io/values/migrations

-   name: "Running Backend service"
    become: true
    shell: |
        cd /home/ubuntu/backend    
        pm2 start npm --no-automation --name "backend" -- run start
