---
-   name: "Installing git"
    become: true
    apt:
        name: git
        state: latest
        update_cache: yes

-   name: "Cloning repo"
    become: true
    git:
        # repo: 'git@github.com:madhur-taneja/Udapeople.git'
        repo: git://github.com/madhur-taneja/Udapeople.git
        clone: yes
        dest: /srv/checkout
        version: master