---
        
- name: "install dist from production build"
    copy:
      src: /root/project/backend/dist/
      dest: /home/ubuntu
      backup: yes
        
-   name: Executing node
    shell: |
        npm install
        pm2 start dist/main.js