version: 2.1
orbs:
    node: circleci/node@1.1.6
jobs:
    # Configuring Infrastructure
    configuring-infrastructure:
        docker:
            - image: python:3.7-alpine3.11
        steps:
            - checkout
            - add_ssh_keys:
                  fingerprints: ["25:f3:77:b4:e3:a0:93:17:29:ed:8c:56:b9:c8:2d:a8"] # You can get this ID in the section where you registered the SSH Key
            - run:
                  name: Install dependencies
                  command: |
                      apk add --update ansible # install the dependencies needed for your playbook
            - attach_workspace:
                  at: .circleci/ansible/
            - run:
                  name: configuring server
                  command: |
                      cat ./.circleci/ansible/inventory
                      pwd
                      cd .circleci/ansible && ansible-playbook -i inventory playbook.yml

    # Creating Inventory with new EC2's IP address
    creating-inventory:
        docker:
            - image: amazon/aws-cli
        steps:
            - checkout
            - run:
                name: Get the IP Address of the EC2 instance 
                command: |
                    echo -e "[web]\n" > ./.circleci/ansible/inventory
                    aws ec2 describe-instances \
                    --query 'Reservations[*].Instances[*].PublicIpAddress' \
                    --output text >> ./.circleci/ansible/inventory
                    cat ./.circleci/ansible/inventory
                    pwd
            - run:
                name: Storing the Backend IP Address to Memstash as Frontend needs it 
                command: |
                    ip_address=$(tail -n 1 ./.circleci/ansible/inventory)
                    echo $ip_address
                    curl -H "Content-Type: text/plain" -H "token: c20424ec-3f12-4c18-87f3-4ce676c7e8ae" --request PUT --data $ip_address https://api.memstash.io/values/backend
            - run:
                name: Install tar/gzip utility
                command: |
                    yum -y install tar
                    yum -y install gzip
            - persist_to_workspace:
                root: .circleci/ansible
                paths:
                    - inventory

    # Creating Infrastructure
    creating-infrastructure:
        docker:
            - image: amazon/aws-cli
        steps:
            - checkout
            # - run:
            #       name: Ensure Cloudfront and Network infrastructure exist
            #       command: |
            #             aws cloudformation deploy \
            #                 --template-file ./.circleci/files/cloudfront.yml \
            #                 --stack-name udapeople-cloudfront-stack \
            #                 --parameter-overrides WorkflowID=${CIRCLE_WORKFLOW_ID:0:7}
            #             aws cloudformation deploy \
            #                 --template-file ./.circleci/files/network.yml \
            #                 --stack-name udapeople-network-stack \
            #                 --parameter-overrides EnvironmentName=${UdaPeople-Env}
            - run:
                  name: Ensure Frontend & Backend infrastructure exist
                  command: |
                        aws cloudformation deploy \
                            --template-file ./.circleci/files/backend.yml \
                            --stack-name udapeople-backend-stack \
                            --parameter-overrides ID=${CIRCLE_WORKFLOW_ID:0:7}
                        aws cloudformation deploy \
                            --template-file ./.circleci/files/frontend.yml \
                            --stack-name udapeople-frontend-stack \
                            --parameter-overrides ID=${CIRCLE_WORKFLOW_ID:0:7}
            # - run:
            #     name: Rollback Cloudfront and Network infrastructure
            #     when: on_fail
            #     command: |       
            #           aws cloudformation delete-stack --stack-name udapeople-cloudfront-stack
            #           aws cloudformation delete-stack --stack-name udapeople-network-stack
            - run:
                name: Rollback Frontend & Backend infrastructure
                when: on_fail
                command: |
                      aws cloudformation delete-stack --stack-name udapeople-backend-stack
                      aws cloudformation delete-stack --stack-name udapeople-frontend-stack  

    # Analyzing Code
    analyzing-backend:
        executor:
            name: node/default
        steps:
            - checkout
            - run: cd backend && npm i && npm audit fix --audit-level=critical --force
    analyzing-frontend:
        executor:
            name: node/default
        steps:
            - checkout
            - run: cd frontend && npm i && npm audit fix --audit-level=critical --force

    # Testing Code
    testing-frontend:
        executor:
            name: node/default
        steps:
            - checkout
            - run: cd frontend && npm i && npm run test

    testing-backend:
        executor:
            name: node/default
        steps:
            - checkout
            - run: cd backend && npm i && npm run test

    # Building Code
    building-frontend:
        executor:
            name: node/default
        steps:
            - checkout
            - run: cd frontend && npm i && npm run build

    building-backend:
        executor:
            name: node/default
        steps:
            - checkout
            - run: cd backend && npm i && npm run build

workflows:
    analyzing-testing-building-deploying:
        jobs:
            # Running Analysis Jobs
            # - analyzing-backend
            # - analyzing-frontend

            # Running Test Jobs
            # - testing-frontend:
            #     requires:
            #         - analyzing-frontend
            # - testing-backend:
            #     requires:
            #         - analyzing-backend

            # Running Build Jobs
            # - building-backend:
            #     requires:
            #         - testing-backend
            # - building-frontend:
            #     requires:
            #         - testing-frontend
            #         - building-backend

            # Running Infrastructure Jobs
            - creating-infrastructure
            #    requires:
            #          - building-frontend
            - creating-inventory:
               requires:
                     - creating-infrastructure
            - configuring-infrastructure:
                  requires:
                      - creating-inventory
                            


