version: 2.1
orbs:
    node: circleci/node@1.1.6

# Common commands among jobs 
commands:
    # Destroying Infrastructure
    rollback-infrastructure:
        steps:
        # - run:
        #     when: on_fail
        #     name: "Destroying Cloudfront and Network infrastructure"
        #     command: |
        #         aws cloudformation delete-stack --stack-name network-stack
        #         aws cloudformation delete-stack --stack-name cloudfront-stack
        - run:
            when: on_fail
            name: "Destroying Frontend & Backend infrastructure"
            command: |
                aws cloudformation delete-stack --stack-name backend-stack
                aws cloudformation delete-stack --stack-name frontend-stack

    # Reverting Database Migration
    rollback-database:
        steps:
        - run:
            when: on_fail
            name: "Database Rollback to previous migration"
            command: |
                cd backend && npm i
                if (( $( curl -H "token: b5e154a8-0ab1-41c6-8855-47f61d4f7873" --request GET https://api.memstash.io/values/migrations ) == 0 ))
                then 
                npm run migrations:revert
                echo "Reverting migrations"
                else
                echo "Migrations not reverted"
                fi
        - run:
            when: on_fail
            name: "Halting the workflow"
            command: |
                circleci-agent step halt

jobs:
    # Building Code
    building-backend:
        docker:
            - image: circleci/node:13.8.0
        steps:
            - checkout
            - run: 
                name: "Installing packages and Building Code"
                command: |
                    sudo npm install webpack-dev-server -g
                    cd backend
                    sudo npm i 
                    sudo npm run build
            # - persist_to_workspace:
            #     root: ~/project
            #     paths:
            #         - backend

    building-frontend:
        docker:
            - image: circleci/node:13.8.0
        steps:
            - checkout
            
            - run: 
                name: "Installing packages and Building Code"
                command: |
                    sudo npm install webpack-dev-server -g
                    cd frontend
                    sudo npm i 
                    sudo npm run build
            # - persist_to_workspace:
            #     root: ~/project
            #     paths:
            #         - frontend

    # Testing Code
    testing-backend:
        docker:
            - image: circleci/node:13.8.0
        steps:
            - checkout
            - run:
                  name: "Installing JUnit and coverage"
                  command: |
                        yarn add --dev jest
                        yarn add --dev jest-junit
            - run:
                  name: "Running tests for Backend with JUnit as reporter"
                  command: |
                      sudo npm install webpack-dev-server -g
                      cd backend
                      mkdir junit
                      sudo npm i
                      sudo npm run test-circleci
            - store_artifacts:
                  path: ./backend/junit
                  destination: junit
            - store_test_results:
                  path: ./backend/junit

    testing-frontend:
        docker:
            - image: circleci/node:13.8.0
        steps:
            - checkout
            - run:
                  name: "Installing JUnit and coverage"
                  command: |
                        yarn add --dev jest
                        yarn add --dev jest-junit
            - run:
                  name: "Running tests for Frontend with JUnit as reporter"
                  command: |
                      sudo npm install webpack-dev-server -g
                      cd frontend
                      mkdir junit
                      sudo npm i
                      sudo npm run test-circleci
            - store_artifacts:
                  path: ./frontend/junit
                  destination: junit
            - store_test_results:
                  path: ./frontend/junit

    # Analyzing Code
    analyzing-backend:
        docker:
            - image: circleci/node:13.8.0
        steps:
            - checkout
            - run: 
                name: "Running audit for Backend"
                command: |
                    cd backend
                    sudo npm i
                    sudo npm audit fix --audit-level=critical --force
    analyzing-frontend:
        docker:
            - image: circleci/node:13.8.0
        steps:
            - checkout
            - run: 
                name: "Running audit for Frontend"
                command: |
                    cd frontend
                    sudo npm i
                    sudo npm audit fix --audit-level=critical --force

    # Smoke Testing Services
    smoke-test:
        docker:
            - image: circleci/node:13.8.0
        steps:
            - checkout
            - run:
                name: "Backend Smoke Test"
                command: |
                    API_HOST=$(curl -H "token: b5e154a8-0ab1-41c6-8855-47f61d4f7873" --request GET https://api.memstash.io/values/backend)     
                    export API_URL=http://$API_HOST:3030
                    if curl "http://${API_URL}:3030/api/status" | grep "statusCode"
                    then
                    return 1
                    else
                    return 0
                    fi
            - run:
                name: "Frontend Smoke Test"
                command: |
                    URL="http://udapeople-f237b39.s3-website-us-east-1.amazonaws.com/#/employees"            
                    if curl -s ${URL} | grep "Welcome"
                    then
                    return 1
                    else
                    return 0
                    fi
            - rollback-infrastructure
            - rollback-database

    # Configuring Frontend Infrastructure
    configuring-frontend-infrastructure:
        docker:
            - image: circleci/node:13.8.0
        steps:
            - checkout
            - run:
                name: "Baking backend API_URL into the front-end"
                command: | 
                    API_HOST=$(curl -H "token: b5e154a8-0ab1-41c6-8855-47f61d4f7873" --request GET https://api.memstash.io/values/backend)     
                    export API_URL=http://$API_HOST:3030
                    echo $API_URL >> frontend/.env
                    cd frontend && npm i && npm run build
            - run:
                name: "Installing AWS-CLI"
                command: |
                    curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
                    unzip awscliv2.zip
                    sudo ./aws/install
            - run:
                name: "Copying compiled files to the S3 Bucket"
                command: |
                    aws s3 cp ./frontend/dist s3://udapeople-f237b39 --recursive

    # Configuring Backend Infrastructure
    configuring-backend-infrastructure:
        docker:
            - image: python:3.7-alpine3.11
        steps:
            - checkout
            - add_ssh_keys:
                fingerprints: ["4d:91:21:13:be:f2:fb:51:78:7d:ff:8f:01:18:6c:21"] # You can get this ID in the section where you registered the SSH Key
            - run:
                name: Install dependencies
                command: |
                    apk add --update ansible # install the dependencies needed for your playbook
            - attach_workspace:
                at: ~/project
            - run:
                name: "Configuring server"
                command: |
                    cat ./.circleci/ansible/inventory
                    pwd
                    cd .circleci/ansible && ansible-playbook -i inventory playbook.yml

    # Creating Inventory with new EC2's IP address
    creating-inventory:
        docker:
            - image: amazon/aws-cli
        steps:
            - checkout
            - run:
                name: Get the IP Address of the EC2 instance 
                command: |
                    echo -e "[web]\n" > ./.circleci/ansible/inventory
                    aws ec2 describe-instances \
                    --query 'Reservations[*].Instances[*].PublicIpAddress' \
                    --output text >> ./.circleci/ansible/inventory
                    cat ./.circleci/ansible/inventory
                    pwd
            - run:
                name: Storing the Backend IP Address to Memstash as Frontend needs it 
                command: |
                    ip_address=$(tail -n 1 ./.circleci/ansible/inventory)
                    echo $ip_address
                    curl -H "Content-Type: text/plain" -H "token: b5e154a8-0ab1-41c6-8855-47f61d4f7873" --request PUT --data $ip_address https://api.memstash.io/values/backend
            - run:
                name: Install tar/gzip utility
                command: |
                    yum -y install tar gzip
            - persist_to_workspace:
                root: ~/project
                paths:
                    - ./.circleci/ansible/inventory

    # Creating Infrastructure
    creating-infrastructure:
        docker:
            - image: amazon/aws-cli
        steps:
            - checkout
            # - run:
            #     name: Ensure Network & Cloudfront infrastructure exist
            #     command: |
            #             aws cloudformation deploy \
            #                 --template-file ./.circleci/files/network.yml \
            #                 --stack-name udapeople-network-stack \
            #                 --parameter-overrides EnvironmentName=${UdaPeople-Env}
            #             aws cloudformation deploy \
            #                 --template-file ./.circleci/files/cloudfront.yml \
            #                 --stack-name udapeople-cloudfront-stack \
            #                 --parameter-overrides WorkflowID=${CIRCLE_WORKFLOW_ID:0:7}
            - run:
                name: Ensure Backend & Frontend infrastructure exist
                command: |
                        aws cloudformation deploy \
                            --template-file ./.circleci/files/backend.yml \
                            --stack-name udapeople-backend-stack \
                            --parameter-overrides ID=${CIRCLE_WORKFLOW_ID:0:7}
                        aws cloudformation deploy \
                            --template-file ./.circleci/files/frontend.yml \
                            --stack-name udapeople-frontend-stack \
                            --parameter-overrides ID=${CIRCLE_WORKFLOW_ID:0:7}
            - rollback-infrastructure

workflows:
    analyzing-testing-building-deploying:
        jobs:
            # Running Analysis Jobs
            # - analyzing-backend
            # - analyzing-frontend

            # Running Test Jobs
            # - testing-frontend:
            #     requires:
            #         - analyzing-frontend
            # - testing-backend:
            #     requires:
            #         - analyzing-backend

            # Running Build Jobs
            # - building-backend:
            #     requires:
            #         - testing-backend
            # - building-frontend:
                # requires:
                #     - testing-frontend
                #     - building-backend

            # Running Infrastructure Jobs
            # - creating-infrastructure
            #     requires:
            #         - building-frontend
            - creating-inventory
                # requires:
                #     - creating-infrastructure
            - configuring-backend-infrastructure:
                requires:
                    - creating-inventory
            - configuring-frontend-infrastructure:
                requires:
                    - configuring-backend-infrastructure
            - smoke-test:
                requires:
                    - configuring-frontend-infrastructure