version: 2.1
orbs:
    node: circleci/node@1.1.6

# Common commands among jobs 
commands:
    # Destroying Infrastructure
    rollback-infrastructure:
        steps:
        # - run:
        #     when: on_fail
        #     name: "Destroying Cloudfront and Network infrastructure"
        #     command: |
        #         aws cloudformation delete-stack --stack-name network-stack
        #         aws cloudformation delete-stack --stack-name cloudfront-stack
        - run:
            when: on_fail
            name: "Destroying Frontend & Backend infrastructure"
            command: |
                aws cloudformation delete-stack --stack-name backend-stack
                aws cloudformation delete-stack --stack-name frontend-stack

    # Reverting Database Migration
    rollback-database:
        steps:
        - run:
            when: on_fail
            name: "Database Rollback to previous migration"
            command: |
                cd backend && npm i
                if (( $( curl -H "token: 476e5d93-3bfe-4549-89d1-d7f73212ec47" --request GET https://api.memstash.io/values/migrations ) == 0 ))
                then 
                npm run migrations:revert
                echo "Reverting migrations"
                else
                echo "Migrations not reverted"
                fi
        - run:
            when: on_fail
            name: "Halting the workflow"
            command: |
                circleci-agent step halt

jobs:
    # Building Code
    building-backend:
        docker:
            - image: circleci/node:13.8.0
        steps:
            - checkout
            - run: 
                name: "Installing packages and Building Code"
                command: |
                    sudo npm install webpack-dev-server -g
                    cd backend
                    sudo npm i 
                    sudo npm run build
            # - persist_to_workspace:
            #     root: ~/project
            #     paths:
            #         - backend

    building-frontend:
        docker:
            - image: circleci/node:13.8.0
        steps:
            - checkout
            
            - run: 
                name: "Installing packages and Building Code"
                command: |
                    sudo npm install webpack-dev-server -g
                    cd frontend
                    sudo npm i 
                    sudo npm run build
            # - persist_to_workspace:
            #     root: ~/project
            #     paths:
            #         - frontend

    # Testing Code
    testing-backend:
        docker:
            - image: circleci/node:13.8.0
        steps:
            - checkout
            - run:
                  name: "Installing JUnit and coverage"
                  command: |
                        yarn add --dev jest
                        yarn add --dev jest-junit
            - run:
                  name: "Running tests for Backend with JUnit as reporter"
                  command: |
                      sudo npm install webpack-dev-server -g
                      cd backend
                      mkdir junit
                      sudo npm i
                      sudo npm run test-circleci
            - store_artifacts:
                  path: ./backend/junit
                  destination: junit
            - store_test_results:
                  path: ./backend/junit

    testing-frontend:
        docker:
            - image: circleci/node:13.8.0
        steps:
            - checkout
            - run:
                  name: "Installing JUnit and coverage"
                  command: |
                        yarn add --dev jest
                        yarn add --dev jest-junit
            - run:
                  name: "Running tests for Frontend with JUnit as reporter"
                  command: |
                      sudo npm install webpack-dev-server -g
                      cd frontend
                      mkdir junit
                      sudo npm i
                      sudo npm run test-circleci
            - store_artifacts:
                  path: ./frontend/junit
                  destination: junit
            - store_test_results:
                  path: ./frontend/junit

    # Analyzing Code
    analyzing-backend:
        docker:
            - image: circleci/node:13.8.0
        steps:
            - checkout
            - run: 
                name: "Running audit for Backend"
                command: |
                    cd backend
                    sudo npm i
                    sudo npm audit fix --audit-level=critical --force
    analyzing-frontend:
        docker:
            - image: circleci/node:13.8.0
        steps:
            - checkout
            - run: 
                name: "Running audit for Frontend"
                command: |
                    cd frontend
                    sudo npm i
                    sudo npm audit fix --audit-level=critical --force

    # Creating Infrastructure
    creating-infrastructure:
        docker:
            - image: amazon/aws-cli
        steps:
            - checkout
            - run:
                name: "Ensure Network Infrastructure exist"
                command: |
                    aws cloudformation deploy \
                        --template-file ./.circleci/files/network.yml \
                        --stack-name udapeople-network-stack \
                        --parameter-overrides EnvironmentName=UdaPeople-Env
            - run:
                name: "Ensure Backend Infrastructure exist"
                command: |
                    aws cloudformation deploy \
                        --template-file ./.circleci/files/backend.yml \
                        --stack-name udapeople-backend-stack-${CIRCLE_WORKFLOW_ID:0:7} \
                        --parameter-overrides ID=${CIRCLE_WORKFLOW_ID:0:7}
            - run:
                name: "Ensure Frontend Infrastructure exist"
                command: |
                    aws cloudformation deploy \
                        --template-file ./.circleci/files/frontend.yml \
                        --stack-name udapeople-frontend-stack-${CIRCLE_WORKFLOW_ID:0:7} \
                        --parameter-overrides ID=${CIRCLE_WORKFLOW_ID:0:7}
            - rollback-infrastructure

    # Creating Inventory with new EC2's IP address
    creating-inventory:
        docker:
            - image: amazon/aws-cli
        steps:
            - checkout
            - run:
                name: "Get the IP Address of the EC2 instance"
                command: |
                    echo -e "[web]\n" > ./.circleci/ansible/inventory
                    aws ec2 describe-instances \
                    --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" \
                    --query 'Reservations[*].Instances[*].PublicIpAddress' \
                    --output text >> ./.circleci/ansible/inventory
                    cat ./.circleci/ansible/inventory
                    pwd
            - run:
                name: "Storing the Backend IP Address to Memstash as Frontend needs it"
                command: |
                    ip_address=$(tail -n 1 ./.circleci/ansible/inventory)
                    echo $ip_address
                    curl -H "Content-Type: text/plain" -H "token: 476e5d93-3bfe-4549-89d1-d7f73212ec47" --request PUT --data $ip_address https://api.memstash.io/values/backend
            - run:
                name: Install tar/gzip utility
                command: |
                    yum -y install tar gzip
            - persist_to_workspace:
                root: ~/project
                paths:
                    - ./.circleci/ansible/inventory
            - rollback-infrastructure

    # Configuring Backend Infrastructure
    configuring-backend-infrastructure:
        docker:
            - image: python:3.7-alpine3.11
        steps:
            - checkout
            - add_ssh_keys:
                fingerprints: ["4d:91:21:13:be:f2:fb:51:78:7d:ff:8f:01:18:6c:21"] # You can get this ID in the section where you registered the SSH Key
            - attach_workspace:
                at: ~/project
            - run:
                name: "Adding .env file for Backend"
                command: |
                    echo -e "NODE_ENV=production\n
                        VERSION=1\n
                        TYPEORM_CONNECTION=${TYPEORM_CONNECTION}\n
                        TYPEORM_MIGRATIONS_DIR=${TYPEORM_MIGRATIONS_DIR}\n
                        TYPEORM_ENTITIES=${TYPEORM_ENTITIES}\n
                        TYPEORM_MIGRATIONS=${TYPEORM_MIGRATIONS}\n
                        TYPEORM_HOST=${TYPEORM_HOST}\n
                        TYPEORM_PORT=${TYPEORM_PORT}\n
                        TYPEORM_USERNAME=${TYPEORM_USERNAME}\n
                        TYPEORM_PASSWORD=${TYPEORM_PASSWORD}\n
                        TYPEORM_DATABASE=${TYPEORM_DATABASE}\n
                        ENVIRONMENT=production" > ./backend/.env
                    cat ./backend/.env
            - persist_to_workspace:
                root: ~/project
                paths:
                    - ./backend/.env
            - run:
                name: "Installing dependencies"
                command: |
                    apk add --update ansible && pip install awscli # install the dependencies needed for your playbook            
            - run:
                name: "Configuring server"
                command: |
                    cat ./.circleci/ansible/inventory
                    pwd
                    cd .circleci/ansible && ansible-playbook -i inventory playbook-configure.yml
            - rollback-infrastructure

    # Configuring Frontend
    configuring-frontend:
        docker:
            - image: circleci/node:13.8.0
        steps:
            - checkout
            - install-aws
            - run:
                name: "Adding .env file for Frontend"
                command: |
                    API_HOST=$(curl -H "token: 476e5d93-3bfe-4549-89d1-d7f73212ec47" --request GET https://api.memstash.io/values/backend)     
                    export API_URL=http://$API_HOST:3030
                    echo "API_URL=$API_URL" >> frontend/.env
            - run:
                name: "Baking backend API_URL into the front-end"
                command: |
                    sudo npm install webpack-dev-server -g
                    cd frontend
                    sudo npm i
                    sudo npm run build
            - persist_to_workspace:
                root: ~/project
                paths:
                    - ./frontend
            - rollback-infrastructure

    # Deploying Backend
    deploying-backend:
        docker:
            - image: python:3.7-alpine3.11
        steps:
            - checkout
            - add_ssh_keys:
                fingerprints: ["4d:91:21:13:be:f2:fb:51:78:7d:ff:8f:01:18:6c:21"] # You can get this ID in the section where you registered the SSH Key
            - run:
                name: "Installing dependencies"
                command: |
                    apk add --update ansible && pip install awscli # install the dependencies needed for your playbook
            - attach_workspace:
                at: ~/project
            - run:
                name: "Deploying code on server"
                command: |
                    cat ./.circleci/ansible/inventory
                    pwd
                    cd .circleci/ansible && ansible-playbook -i inventory playbook-deploy.yml
            - rollback-infrastructure

    # Deploying Frontend
    deploying-frontend:
        docker:
            - image: amazon/aws-cli
        steps:
            - run:
                name: Install tar/gzip utility
                command: |
                    yum -y install tar gzip
            - attach_workspace:
                at: ~/project
            - run:
                name: "Copying compiled files to the S3 Bucket"
                command: |
                    cat ./frontend/.env
                    aws s3 cp ./frontend/dist s3://udapeople-${CIRCLE_WORKFLOW_ID:0:7} --recursive
            - rollback-infrastructure

    # Smoke Testing Services
    smoke-testing:
        docker:
            -   image: circleci/node:13.8.0
        steps:
            - checkout
            - install-aws
            - run:
                name: "Backend Smoke Test"
                command: |
                    API_HOST=$(curl -H "token: 476e5d93-3bfe-4549-89d1-d7f73212ec47" --request GET https://api.memstash.io/values/backend)
                    export API_URL=http://$API_HOST:3030
                    function backendSmokeTest
                    {
                        if (( $( curl -s ${API_URL}/api/status | grep -c status ) == 0 ))
                        then return 1;
                        else return 0;
                        fi
                    }
                    backendSmokeTest
            - run:
                name: "Frontend Smoke Test"
                command: |
                    URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-us-east-1.amazonaws.com/#/employees"
                    function frontendSmokeTest
                    {
                        if (( $( curl -s ${URL} | grep -c Welcome ) > 0 ))
                        then return 0; 
                        else return 1; 
                        fi
                    }
                    frontendSmokeTest
            - rollback-infrastructure
            - rollback-database

workflows:
    analyzing-testing-building-deploying:
        jobs:
            # Running Analysis Jobs
            # - analyzing-backend
            # - analyzing-frontend

            # Running Test Jobs
            # - testing-frontend:
            #     requires:
            #         - analyzing-frontend
            # - testing-backend:
            #     requires:
            #         - analyzing-backend

            # Running Build Jobs
            # - building-backend:
            #     requires:
            #         - testing-backend
            # - building-frontend:
                # requires:
                #     - testing-frontend
                #     - building-backend

            # Running Infrastructure Jobs
            # - creating-infrastructure
            #     requires:
            #         - building-frontend
            - creating-inventory
                # requires:
                #     - creating-infrastructure
            - configuring-backend-infrastructure:
                requires:
                    - creating-inventory
            - configuring-frontend-infrastructure:
                requires:
                    - configuring-backend-infrastructure
            - smoke-test:
                requires:
                    - configuring-frontend-infrastructure