version: 2.1
orbs:
    node: circleci/node@1.1.6
jobs:
    building-frontend:
        executor:
            name: node/default
        steps:
            - checkout
            - run: cd frontend && npm i && npm run build 

    building-backend:
        executor:
            name: node/default
        steps:
            - checkout
            - run: cd backend && npm i && npm run build
      
workflows:
    building:
        jobs:
            - building-backend                
            - building-frontend:
                requires:
                    - building-backend