---
- name: "Installing alert manager"
  unarchive:
    src: https://github.com/prometheus/alertmanager/releases/download/v0.21.0/alertmanager-0.21.0.linux-amd64.tar.gz
    dest: /tmp
    remote_src: yes

- name: "Moving multiple binaries"
  become: true
  copy: src= "/tmp/alertmanager-0.21.0.linux-amd64/{{ item.src }}" dest= "/usr/local/bin/{{ item.dest }}"
  remote_src: yes
  mode: '0777'
  with_items:
    - { src: 'alertmanager', dest: 'alertmanager' }
    - { src: 'amtool', dest: 'amtool' }

- name: "Making directory and removing junk files"
  become: true
  shell: |
    mkdir /var/lib/alertmanager
    rm -rf alertmanager*

- name: "Adding alert manager configurations"
  become: true
  copy: src= "{{ item.src }}" dest= "{{ item.dest }}"
  with_items:
    - { src: 'alertmanager.yml', dest: '/etc/prometheus/' }
    - { src: 'rules.yml', dest: '/etc/prometheus/' }
    - { src: 'alertmanager.service', dest: '/etc/systemd/system/' }

- name: "Enabling alert manager service"
  become: true
  systemd:
    state: restarted
    daemon_reload: yes
    name: alertmanager
    enabled: yes

- name: "Changing the permissions of the directories, files and binaries"
  become: true
  shell: |
    chown -R prometheus:prometheus /etc/prometheus